<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <Features>strict</Features>
        <AnalysisLevel>latest-recommended</AnalysisLevel>

        <VersionPrefix>$([System.DateTime]::Now.ToString("yy.M.d.Hmm"))</VersionPrefix>
        <Copyright>Copyright $([System.DateTime]::Now.Year) © 2D Soluciones</Copyright>
        <Company>2D Soluciones</Company>
    </PropertyGroup>

    <PropertyGroup>
		<NoWarn>CA1707,CS1591,CA2201,CA1720,IDE0060,CA1848</NoWarn>
	</PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4"/>
    </ItemGroup>
</Project>
